development:
  adapter: mysql2
  encoding: utf8
  database: AFFICHE
  pool: 5
  username: lab6
  password: 12
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: AFFICHE
  pool: 5
  username: lab6
  password: 12
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: AFFICHE
  pool: 5
  username: lab6
  password: 12
  socket: /var/run/mysqld/mysqld.sock